name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: pwd
    - name: Run a multi-line script
      run: |
        cd /home/runner/work/hello-world/hello-world/scripts/config
        chmod 777 SPLookUpXML.sh
        ./SPLookUpXML.sh
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v2
      with:
        name: SPXMLFiles
        path: /home/runner/work/hello-world/hello-world/scripts/config/
      
