name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Test shell command for current path
      run: pwd
    - name: Execute the look up Script
      run: |
        cd /home/runner/work/hello-world/hello-world/scripts/config
        chmod 777 SPLookUpXML.sh
        ./SPLookUpXML.sh
    - name: Upload the Sailpoint Generated Artefacts
      uses: actions/upload-artifact@v2
      with:
        name: SPWExport
        path: /home/runner/work/hello-world/hello-world/scripts/config/
      
